version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing Python dependencies..."
      - pip install --upgrade pip
      - pip install boto3 sagemaker==2.224.1
      - |
        if [ -f requirements.txt ]; then 
          pip install -r requirements.txt
        fi
      - |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        AWS_REGION=${AWS_REGION:-us-east-1}
        ECR_REGISTRY="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        REPO_NAME="ml-pipeline-components"
      - echo "Logging into ECR..."
      - |
        aws ecr get-login-password --region ${AWS_REGION} \
        | docker login --username AWS --password-stdin ${ECR_REGISTRY}

  pre_build:
    commands:
      - echo "Detecting changed files..."

      - REBUILD_ALL=false
      - COMPONENTS_TO_BUILD=""
      - PIPELINE_CHANGED=false

      - |
        BASE_COMMIT=$(git rev-parse HEAD~1 2>/dev/null || echo "")
        if [ -z "$BASE_COMMIT" ]; then
          echo "No previous commit found → rebuilding all components"
          REBUILD_ALL=true
        else
          CHANGED_FILES=$(git diff --name-only $BASE_COMMIT HEAD)
        fi
        echo "Changed files:"
        echo "$CHANGED_FILES"

      - |
        if echo "$CHANGED_FILES" | grep -E "components/.*/Dockerfile|requirements.txt" >/dev/null; then
          echo "Dockerfile or requirements changed → rebuild all"
          REBUILD_ALL=true
        fi

      - |
        if [ "$REBUILD_ALL" = false ]; then
          for comp in data_fetcher preprocess train evaluate model_registry; do
            if echo "$CHANGED_FILES" | grep "components/$comp/" >/dev/null; then
              COMPONENTS_TO_BUILD="$COMPONENTS_TO_BUILD $comp"
            fi
          done
        fi

      - |
        if echo "$CHANGED_FILES" | grep "pipeline/pipeline.py" >/dev/null; then
          PIPELINE_CHANGED=true
        fi

      - echo "Components to rebuild: $COMPONENTS_TO_BUILD"
      - echo "Pipeline changed: $PIPELINE_CHANGED"
      - echo "Rebuild all: $REBUILD_ALL"

  build:
    commands:
      - echo "Starting build phase..."

      - |
        if [ "$REBUILD_ALL" = true ]; then
          echo "Rebuilding ALL components..."
          COMPONENTS_TO_BUILD="data_fetcher preprocess train evaluate model_registry"
        fi

      - |
        if [ -n "$COMPONENTS_TO_BUILD" ]; then
          for comp in $COMPONENTS_TO_BUILD; do
            echo "Building Docker image for $comp..."
            docker build -t ${REPO_NAME}-${comp}:latest -f components/$comp/Dockerfile .
            docker tag ${REPO_NAME}-${comp}:latest ${ECR_REGISTRY}/${REPO_NAME}-${comp}:latest
            docker push ${ECR_REGISTRY}/${REPO_NAME}-${comp}:latest
          done
        else
          echo "No component changes → using existing ECR images"
        fi

      - echo "Running SageMaker Pipeline..."
      - python pipeline/pipeline.py

  post_build:
    commands:
      - echo "Build and pipeline execution completed."
